name: relive_app
description: A sustainable app with crypto and eco-friendly features.
publish_to: "none" # Prevent accidental publication to pub.dev.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Chart Library
  syncfusion_flutter_charts: ^20.2.36

  # Firebase dependencies
  firebase_core: ^2.15.0
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.5
  firebase_analytics: ^10.3.0

  # State management
  provider: ^6.1.2

  # UI and Theming
  google_fonts: ^6.2.1

  # Navigation
  go_router: ^8.0.3

  # HTTP Requests
  http: ^1.2.1

  # Crypto and API handling
  crypto: ^3.0.6

  # Animations
  flutter_animate: ^4.1.0

  # For Image Handling
  cached_network_image: ^3.2.3

  # For Loading Spinners
  flutter_spinkit: ^5.2.1

  # Internationalization
  flutter_localizations:
    sdk: flutter

  # Other utilities
  shared_preferences: ^2.3.3
  url_launcher: ^6.2.1

flutter_test:
  patrol: ^3.13.2

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets (Images, Fonts)
  assets:
    - assets/images/logo.png
    - assets/images/splash.png
    - assets/images/background.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
